worker:
  build: .
  ports:
    - 22
  links:
    - db
    - redis
    - memcached

db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root

redis:
  image: redis

memcached:
  image: memcached